'use client';
import { FormEvent, use, useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { Meeting } from '@/lib/types';
import { StatusBadge } from '@/components/StatusBadge';
import { TranscriptViewer } from '@/components/TranscriptViewer';
import { MediaPlayer } from '@/components/MediaPlayer';

export default function MeetingDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [meeting,setMeeting]=useState<Meeting|null>(null);const [error,setError]=useState('');const [uploading,setUploading]=useState(false);const [artifactType,setArtifactType]=useState('uploaded_transcript');
 const load=useCallback(()=>api<Meeting>(`/meetings/${id}`).then(setMeeting).catch(e=>setError(e.message)),[id]);useEffect(()=>{void load();},[load]);
 const upload=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('file') as HTMLInputElement;if(!input.files?.[0])return;setUploading(true);setError('');const body=new FormData();body.append('artifact_type',artifactType);body.append('file',input.files[0]);try{await api(`/meetings/${id}/artifacts`,{method:'POST',body});input.value='';await load();}catch(err){setError(err instanceof Error?err.message:'Upload failed');}finally{setUploading(false);}};
 if(!meeting)return <div className="center-screen"><div className="loader"/><p>Loading meeting...</p></div>;
 const transcript=meeting.current_transcript;
 const recording=meeting.artifacts?.find(artifact=>artifact.artifact_type==='audio'||artifact.artifact_type==='video');
 return <div><header className="page-header"><div><span className="eyebrow">{meeting.provider.toUpperCase()}</span><h1>{meeting.title}</h1><p>Meeting ID {meeting.id}</p></div><StatusBadge value={meeting.status}/></header>{error&&<div className="error-box">{error}</div>}<section className="detail-grid"><div className="panel"><div className="panel-heading"><div><h2>Source artifacts</h2><p>Original files are checksum-linked and processed asynchronously.</p></div></div><form className="upload-box" onSubmit={upload}><select value={artifactType} onChange={e=>setArtifactType(e.target.value)}><option value="uploaded_transcript">Uploaded transcript</option><option value="provider_transcript">Provider transcript</option><option value="audio">Audio recording</option><option value="video">Video recording</option></select><input name="file" type="file" accept=".vtt,.txt,.md,audio/*,video/*" required/><button className="primary-button" disabled={uploading}>{uploading?'Uploading...':'Upload & process'}</button></form><div className="artifact-list">{meeting.artifacts?.map(a=><div className="artifact-card" key={a.id}><div className="file-icon">{a.artifact_type.includes('transcript')?'TXT':'AV'}</div><div><strong>{a.original_filename??a.artifact_type}</strong><small>{a.artifact_type.replaceAll('_',' ')} · {a.file_size?`${Math.round(a.file_size/1024)} KB`:'size unavailable'}</small></div><StatusBadge value={a.status}/></div>)}{!meeting.artifacts?.length&&<p className="muted">No artifacts have been uploaded.</p>}</div></div><aside className="panel"><div className="panel-heading"><div><h2>Processing</h2><p>Queue and AI service state.</p></div></div><div className="process-state"><StatusBadge value={meeting.processing_status}/><button className="secondary-button" onClick={()=>void load()}>Refresh</button></div><div className="job-list">{meeting.processing_jobs?.map(job=><div key={job.id}><span>{job.stage}</span><StatusBadge value={job.status}/>{job.error_message&&<small className="error-text">{job.error_message}</small>}</div>)}</div></aside></section>{recording&&<section className="panel recording-panel"><div className="panel-heading"><div><h2>Source recording</h2><p>Transcript timestamps seek directly into this immutable source artifact.</p></div><span className="checksum-label">SHA-256 linked</span></div><MediaPlayer meetingId={meeting.id} artifactId={recording.id} type={recording.artifact_type as 'audio'|'video'}/></section>}<section className="panel transcript-panel"><div className="panel-heading"><div><h2>Transcript review</h2><p>Click a speaker name to confirm or correct the identity.</p></div>{transcript&&<span className="version-pill">Version {transcript.version_number}</span>}</div>{transcript?.segments?.length?<TranscriptViewer meetingId={meeting.id} initialSegments={transcript.segments}/>:<div className="empty-state"><h3>Transcript not ready</h3><p>Upload the sample VTT file and refresh once the queue has completed processing.</p></div>}</section></div>
}
