<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('provider_accounts',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->string('provider');$t->string('external_account_id')->nullable();$t->text('access_token')->nullable();$t->text('refresh_token')->nullable();$t->timestamp('token_expires_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['tenant_id','provider','external_account_id']);});
 Schema::create('meetings',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('organiser_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('provider')->default('manual');$t->string('provider_meeting_id')->nullable();$t->string('title');$t->text('meeting_url')->nullable();$t->timestampTz('scheduled_start_at')->nullable();$t->timestampTz('actual_start_at')->nullable();$t->timestampTz('actual_end_at')->nullable();$t->string('timezone')->default('UTC');$t->string('status')->default('created');$t->string('capture_mode')->default('post_meeting');$t->string('processing_status')->default('not_started');$t->json('metadata')->nullable();$t->timestamps();$t->index(['tenant_id','status']);$t->unique(['tenant_id','provider','provider_meeting_id']);});
 Schema::create('meeting_artifacts',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('meeting_id')->constrained()->cascadeOnDelete();$t->string('artifact_type');$t->string('source');$t->string('provider_artifact_id')->nullable();$t->string('storage_disk');$t->text('storage_key');$t->string('original_filename')->nullable();$t->string('mime_type')->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->unsignedBigInteger('duration_ms')->nullable();$t->char('checksum_sha256',64);$t->boolean('is_original')->default(true);$t->string('status')->default('stored');$t->json('metadata')->nullable();$t->timestamps();$t->unique(['meeting_id','checksum_sha256']);});
 Schema::create('transcript_versions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('meeting_id')->constrained()->cascadeOnDelete();$t->foreignUuid('source_artifact_id')->nullable()->constrained('meeting_artifacts')->nullOnDelete();$t->unsignedInteger('version_number');$t->string('version_type');$t->string('language',20)->nullable();$t->string('transcription_provider')->nullable();$t->string('model_identifier')->nullable();$t->string('status')->default('processing');$t->boolean('is_current')->default(false);$t->json('metadata')->nullable();$t->timestamps();$t->unique(['meeting_id','version_number']);$t->index(['meeting_id','is_current']);});
 Schema::create('meeting_speakers',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('meeting_id')->constrained()->cascadeOnDelete();$t->string('display_name');$t->string('diarization_label');$t->string('provider_participant_id')->nullable();$t->string('identity_status')->default('unresolved');$t->decimal('identity_confidence',5,4)->nullable();$t->foreignUuid('confirmed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestampTz('confirmed_at')->nullable();$t->timestamps();$t->unique(['meeting_id','diarization_label']);});
 Schema::create('transcript_segments',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('transcript_version_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('sequence');$t->foreignUuid('speaker_id')->nullable()->constrained('meeting_speakers')->nullOnDelete();$t->unsignedBigInteger('start_ms');$t->unsignedBigInteger('end_ms');$t->text('text');$t->decimal('confidence',5,4)->nullable();$t->string('source_reference')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['transcript_version_id','sequence']);$t->index(['transcript_version_id','start_ms']);});
 Schema::create('processing_jobs',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('meeting_id')->constrained()->cascadeOnDelete();$t->string('stage');$t->unsignedSmallInteger('attempt')->default(1);$t->string('status');$t->foreignUuid('input_artifact_id')->nullable()->constrained('meeting_artifacts')->nullOnDelete();$t->foreignUuid('output_transcript_version_id')->nullable()->constrained('transcript_versions')->nullOnDelete();$t->timestampTz('started_at')->nullable();$t->timestampTz('completed_at')->nullable();$t->string('error_code')->nullable();$t->text('error_message')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['meeting_id','stage','status']);});
 Schema::create('evidence_links',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('meeting_id')->constrained()->cascadeOnDelete();$t->string('generated_item_type');$t->uuid('generated_item_id');$t->foreignUuid('recording_artifact_id')->nullable()->constrained('meeting_artifacts')->nullOnDelete();$t->foreignUuid('transcript_version_id')->constrained()->cascadeOnDelete();$t->json('segment_ids');$t->unsignedBigInteger('start_ms');$t->unsignedBigInteger('end_ms');$t->text('evidence_text')->nullable();$t->char('source_checksum',64)->nullable();$t->foreignUuid('created_by_job_id')->nullable()->constrained('processing_jobs')->nullOnDelete();$t->json('metadata')->nullable();$t->timestamps();$t->index(['generated_item_type','generated_item_id']);});
 Schema::create('provider_events',function(Blueprint $t){$t->uuid('id')->primary();$t->string('provider');$t->string('external_event_id');$t->string('event_type');$t->json('payload');$t->string('status')->default('received');$t->timestampTz('processed_at')->nullable();$t->text('error_message')->nullable();$t->timestamps();$t->unique(['provider','external_event_id']);});
 } public function down(): void { foreach(['provider_events','evidence_links','processing_jobs','transcript_segments','meeting_speakers','transcript_versions','meeting_artifacts','meetings','provider_accounts'] as $table){Schema::dropIfExists($table);} } };
